import Image from 'next/image';
import { cn } from '@/lib/utils';

/**
 * The client's own supplied logo.
 *
 * Replaces the hand-authored <Logo /> in the nav, mobile menu and footer.
 *
 * Generated by `npm run logo:prepare` from assets-source/client-logo.png.
 * The source is an orange lockup on transparency, which does not match the
 * site's navy and aqua palette. That is a client decision, recorded in
 * DECISIONS.md, not an oversight.
 *
 * Rendered at 40px tall on desktop and 36px on mobile. The asset is exported
 * at 80px tall so it stays sharp on retina displays.
 */

/** Intrinsic size of public/brand/logo-client.png. Update if the source changes. */
const LOGO = {
  src: '/brand/logo-client.png',
  width: 240,
  height: 80,
};

export function ClientLogo({ className }: { className?: string }) {
  return (
    <Image
      src={LOGO.src}
      alt="Fluid Plumbing Solutions"
      width={LOGO.width}
      height={LOGO.height}
      priority
      className={cn('h-9 w-auto md:h-10', className)}
    />
  );
}
